services:
  matrix-proxy:
    image: matrix-proxy
    pull_policy: if_not_present
    restart: unless-stopped
    hostname: matrix-proxy
    environment:
      BASE_URL: http://0.0.0.0:7654
      HOMESERVER_URL: ${HOMESERVER_URL}
      HOMESERVER_USER: ${HOMESERVER_USER}
      HOMESERVER_PASS: ${HOMESERVER_PASS}
    ports:
      - "127.0.0.1:7654:7654"
